apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sm-soc-secret
  namespace: sm-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sm-soc-secret
    creationPolicy: Owner
  data:
    - secretKey: SM_INTERNAL_API_KEY
      remoteRef:
        key: secret/sm/soc/internal-api-key
        property: value
    - secretKey: SM_SM4_KEY_HEX
      remoteRef:
        key: secret/sm/soc/sm4-key
        property: value
    - secretKey: SM_DATABASE_URL
      remoteRef:
        key: secret/sm/soc/database-url
        property: value
