apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: sm-soc-pod-kill
  namespace: sm-prod
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - sm-prod
    labelSelectors:
      app.kubernetes.io/instance: sm-soc
      app.kubernetes.io/name: sm-soc
  scheduler:
    cron: '@every 30m'
